export { default as Main } from './Main'
export { MainTextOne } from './MainTextOne'
export { MainTextTwo } from './MainTextTwo'
export { MainTextThree } from './MainTextThree'
export { MainTextFour } from './MainTextFour'
